# Generated by Django 4.0 on 2021-12-10 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Sume', '0003_itensordens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('id_prestador', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_inicio_vigencia', models.DateField()),
                ('data_fim_vigencia', models.DateField()),
                ('objeto', models.CharField(max_length=25)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItensContrato',
            fields=[
                ('id_item_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.IntegerField()),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Sume.contratos')),
                ('id_item_ordem', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Sume.itensordens')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_alt', to='auth.user')),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_cad', to='auth.user')),
            ],
        ),
    ]
