# Generated by Django 4.0 on 2021-12-10 20:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Sume', '0004_contratos_itenscontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigencias',
            fields=[
                ('id_vigencia', models.AutoField(primary_key=True, serialize=False)),
                ('dt_inicio_vigencia', models.DateField()),
                ('dt_fim_vigencia', models.DateField()),
                ('valor', models.IntegerField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='Sume.contratos')),
            ],
        ),
    ]
