# Generated by Django 3.2.9 on 2021-12-11 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sume', '0005_vigencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensContratos',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_item_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Itens Contratos',
                'db_table': 'ItensContratos',
                'ordering': ['id_contrato'],
            },
        ),
        migrations.CreateModel(
            name='ItensOrdem',
            fields=[
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_item_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('produto_servico', models.CharField(max_length=150)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.FloatField()),
                ('vinculado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Itens Ordem',
                'db_table': 'ItensOrdem',
                'ordering': ['produto_servico'],
            },
        ),
        migrations.RemoveField(
            model_name='itensordens',
            name='id_ordem',
        ),
        migrations.RemoveField(
            model_name='itensordens',
            name='id_user_alt',
        ),
        migrations.RemoveField(
            model_name='itensordens',
            name='id_user_cad',
        ),
        migrations.AlterModelOptions(
            name='contratos',
            options={'ordering': ['ano'], 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'ordering': ['razao_social'], 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='naturezasdespesa',
            options={'ordering': ['desc_natureza_despesa'], 'verbose_name_plural': 'Naturezas Despesas'},
        ),
        migrations.AlterModelOptions(
            name='ordens',
            options={'ordering': ['ano'], 'verbose_name_plural': 'Ordens'},
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'ordering': ['titulo'], 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='vigencias',
            options={'ordering': ['id_contrato'], 'verbose_name_plural': 'Vigencias'},
        ),
        migrations.RenameField(
            model_name='naturezasdespesa',
            old_name='cod_natureza_despesa',
            new_name='cod_natureza_despesas',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='data_fim_vigencia',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='data_inicio_vigencia',
        ),
        migrations.RemoveField(
            model_name='vigencias',
            name='valor',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='id_prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contratos', to='Sume.fornecedores'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='id_user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_user_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='id_user_cad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_user_cad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='objeto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='id_user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_user_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='id_user_cad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_user_cad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='razao_social',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='telefone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ordens',
            name='id_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ordens', to='Sume.fornecedores'),
        ),
        migrations.AlterField(
            model_name='ordens',
            name='id_natureza_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ordens', to='Sume.naturezasdespesa'),
        ),
        migrations.AlterField(
            model_name='ordens',
            name='id_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ordens', to='Sume.projetos'),
        ),
        migrations.AlterField(
            model_name='ordens',
            name='id_user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_user_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordens',
            name='id_user_cad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordens_user_cad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='id_user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_user_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='id_user_cad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_user_cad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vigencias',
            name='id_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sume.contratos'),
        ),
        migrations.AlterModelTable(
            name='contratos',
            table='Contratos',
        ),
        migrations.AlterModelTable(
            name='fornecedores',
            table='Fornecedores',
        ),
        migrations.AlterModelTable(
            name='naturezasdespesa',
            table='NaturezasDespesa',
        ),
        migrations.AlterModelTable(
            name='ordens',
            table='Ordens',
        ),
        migrations.AlterModelTable(
            name='projetos',
            table='Projetos',
        ),
        migrations.AlterModelTable(
            name='vigencias',
            table='Vigencias',
        ),
        migrations.DeleteModel(
            name='ItensContrato',
        ),
        migrations.DeleteModel(
            name='ItensOrdens',
        ),
        migrations.AddField(
            model_name='itensordem',
            name='id_ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sume.ordens'),
        ),
        migrations.AddField(
            model_name='itensordem',
            name='id_user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itensordem_user_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itensordem',
            name='id_user_cad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itensordem_user_cad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itenscontratos',
            name='id_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sume.contratos'),
        ),
        migrations.AddField(
            model_name='itenscontratos',
            name='id_item_ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sume.itensordem'),
        ),
        migrations.AddField(
            model_name='itenscontratos',
            name='id_user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itenscontratos_user_alt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itenscontratos',
            name='id_user_cad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itenscontratos_user_cad', to=settings.AUTH_USER_MODEL),
        ),
    ]
